name: jinju_tour_app
description: "A Flutter app for Jinju Tour, based on the React project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  table_calendar: ^3.1.1
  share_plus: ^9.0.0
  http: ^1.2.1
  flutter_riverpod: ^2.5.1
  intl: ^0.20.2  # 버전 충돌 해결 반영

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
